#!/bin/bash

echo "🔥 Firebase Setup Helper for Charette System"
echo "=============================================="
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 1
    fi
fi

echo "📋 Firebase Configuration Setup"
echo "-------------------------------"
echo "You'll need to get these values from Firebase Console:"
echo "1. Go to https://console.firebase.google.com/"
echo "2. Select your project (or create new)"
echo "3. Go to Project Settings > General > Your apps"
echo "4. Add a Web app (</>) if you haven't already"
echo "5. Copy the config values"
echo ""

read -p "Do you have your Firebase config ready? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please get your Firebase config first, then run this script again."
    exit 1
fi

echo ""
echo "Enter your Firebase configuration values:"
echo ""

read -p "API Key (REACT_APP_FIREBASE_API_KEY): " api_key
read -p "Auth Domain (REACT_APP_FIREBASE_AUTH_DOMAIN): " auth_domain
read -p "Project ID (REACT_APP_FIREBASE_PROJECT_ID): " project_id
read -p "Storage Bucket (REACT_APP_FIREBASE_STORAGE_BUCKET): " storage_bucket
read -p "Messaging Sender ID (REACT_APP_FIREBASE_MESSAGING_SENDER_ID): " messaging_sender_id
read -p "App ID (REACT_APP_FIREBASE_APP_ID): " app_id
read -p "Measurement ID (optional, REACT_APP_FIREBASE_MEASUREMENT_ID): " measurement_id

# Create .env.local file
cat > .env.local << EOF
# Firebase Configuration
# Generated by setup-firebase.sh

REACT_APP_FIREBASE_API_KEY=$api_key
REACT_APP_FIREBASE_AUTH_DOMAIN=$auth_domain
REACT_APP_FIREBASE_PROJECT_ID=$project_id
REACT_APP_FIREBASE_STORAGE_BUCKET=$storage_bucket
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$messaging_sender_id
REACT_APP_FIREBASE_APP_ID=$app_id
EOF

if [ ! -z "$measurement_id" ]; then
    echo "REACT_APP_FIREBASE_MEASUREMENT_ID=$measurement_id" >> .env.local
fi

echo ""
echo "✅ Firebase configuration saved to .env.local"
echo ""
echo "🔒 Security Reminder:"
echo "The .env.local file is gitignored and will not be committed to version control."
echo "Keep your Firebase credentials secure and never share them publicly."
echo ""
echo "🚀 Next steps:"
echo "1. Run 'npm run dev-full' to start the application"
echo "2. Open http://localhost:3000 in your browser"
echo "3. Sign in with Google to test authentication"
