# Firebase Setup Script for Windows PowerShell
# Run this script to configure Firebase for the Charette System

Write-Host "🔥 Firebase Setup Helper for Charette System" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local already exists
if (Test-Path ".env.local") {
    Write-Host "⚠️  .env.local already exists!" -ForegroundColor Yellow
    $response = Read-Host "Do you want to overwrite it? (y/N)"
    if ($response -notmatch "^[Yy]$") {
        Write-Host "Setup cancelled."
        exit 1
    }
}

Write-Host "📋 Firebase Configuration Setup" -ForegroundColor Green
Write-Host "-------------------------------" -ForegroundColor Green
Write-Host "You'll need to get these values from Firebase Console:" -ForegroundColor White
Write-Host "1. Go to https://console.firebase.google.com/" -ForegroundColor White
Write-Host "2. Select your project (or create new)" -ForegroundColor White
Write-Host "3. Go to Project Settings > General > Your apps" -ForegroundColor White
Write-Host "4. Add a Web app (</>) if you haven't already" -ForegroundColor White
Write-Host "5. Copy the config values" -ForegroundColor White
Write-Host ""

$response = Read-Host "Do you have your Firebase config ready? (y/N)"
if ($response -notmatch "^[Yy]$") {
    Write-Host "Please get your Firebase config first, then run this script again." -ForegroundColor Yellow
    exit 1
}

Write-Host ""
Write-Host "Enter your Firebase configuration values:" -ForegroundColor Green
Write-Host ""

$apiKey = Read-Host "API Key (REACT_APP_FIREBASE_API_KEY)"
$authDomain = Read-Host "Auth Domain (REACT_APP_FIREBASE_AUTH_DOMAIN)"
$projectId = Read-Host "Project ID (REACT_APP_FIREBASE_PROJECT_ID)"
$storageBucket = Read-Host "Storage Bucket (REACT_APP_FIREBASE_STORAGE_BUCKET)"
$messagingSenderId = Read-Host "Messaging Sender ID (REACT_APP_FIREBASE_MESSAGING_SENDER_ID)"
$appId = Read-Host "App ID (REACT_APP_FIREBASE_APP_ID)"
$measurementId = Read-Host "Measurement ID (optional, REACT_APP_FIREBASE_MEASUREMENT_ID)"

# Create .env.local file
$content = @"
# Firebase Configuration
# Generated by setup-firebase.ps1

REACT_APP_FIREBASE_API_KEY=$apiKey
REACT_APP_FIREBASE_AUTH_DOMAIN=$authDomain
REACT_APP_FIREBASE_PROJECT_ID=$projectId
REACT_APP_FIREBASE_STORAGE_BUCKET=$storageBucket
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$messagingSenderId
REACT_APP_FIREBASE_APP_ID=$appId
"@

if ($measurementId -and $measurementId.Trim() -ne "") {
    $content += "`nREACT_APP_FIREBASE_MEASUREMENT_ID=$measurementId"
}

$content | Out-File -FilePath ".env.local" -Encoding UTF8

Write-Host ""
Write-Host "✅ Firebase configuration saved to .env.local" -ForegroundColor Green
Write-Host ""
Write-Host "🔒 Security Reminder:" -ForegroundColor Yellow
Write-Host "The .env.local file is gitignored and will not be committed to version control." -ForegroundColor Yellow
Write-Host "Keep your Firebase credentials secure and never share them publicly." -ForegroundColor Yellow
Write-Host ""
Write-Host "🚀 Next steps:" -ForegroundColor Cyan
Write-Host "1. Run 'npm run dev-full' to start the application" -ForegroundColor White
Write-Host "2. Open http://localhost:3000 in your browser" -ForegroundColor White
Write-Host "3. Sign in with Google to test authentication" -ForegroundColor White
